### ISSUE TITLE
Could not load PED

### ISSUE THREAD

**Issue by Nju79** [AmiBlitz/AmiBlitz3#12]
Hi,
I downloaded the sources from AmiBlitz 3.8.0 and extracted the directory to DH0. If I doubleclick on the Amiblitz3-Icon I get the message

"Kann nicht laden the Editor: Blitz3:System/PED must beenden, sorry!"

in english (translated): "Could not load the editor Blitz3:System/PED" must exit, sorry!"

I saw, "Blitz3" is an assign, so I added to startup-sequence the path to AmiBlitz3-directory.

I get the error again. PED is not executable - I think the file is corrupted?

My config:
Amiga 1200
ACA1221lc
Kickstart 3.1.4/Workbench 3.1.4.1

Next one is: When I doubleclick on the Amiblitz3-Icon the assignment "Blitz3" will deleted. Is this correct? I tested this assign in the shell befor and this was correct.

**Comment by honitos** [comment]
I forgot to tell github to handle PED as binary. It happened because I renamed "PED_Beta" to "PED"...
Updated repository.
