### ISSUE TITLE
Error when moving a line to first position.

### ISSUE THREAD

**Issue by T0lk13n** [AmiBlitz/AmiBlitz3#13]
Using Alt+ cursor to move a line.
If you move it to the first line position it get copied all over the source code (and freeze my morphos machine).
Perhaps you have to move it twice to the first line to catch the error.

**Comment by T0lk13n** [comment]
Tested in an A1200 060 with same result.

**Comment by honitos** [comment]
I am aware of that problem. Will be fixed after rewrite of PED.

**Comment by honitos** [comment]
fixed with v3.9.0
