### ISSUE TITLE
"Delete to EOL" messes up text in front of it

### ISSUE THREAD

**Issue by stevetronic** [AmiBlitz/AmiBlitz3#16]
Using the edit function "Delete to EOL" by pressing the Amiga-Y key messes up tokens in this line, left of the cursor. Their characters are replaced with characters like "ÄÖÜäöü".

![bug-deleteToEol](https://user-images.githubusercontent.com/15176835/92660683-36e65800-f2fb-11ea-93a0-8e34c9b0cf9a.JPG)

Moving the cursur a line up or down will "restore" the contents, so it is not a big problem.
Nevertheless it looks a bit unprofessional and for sure shocks first time users ;)

**Comment by Nju79** [comment]
I can confirm this issue. My machine: Linux Mint with FS-UAE 3.0.5 and Folder as HDD.

> Moving the cursur a line up or down will "restore" the contents, so it is not a big problem.

Big problem: Don't save the file after that. I did and it has changed the encoding of the file so I couldn't edit this file in an texteditor on my main machine nor edit the file in BB2-Editor in the emulator (the characters were changed like the issue). Finally I restored the files from my backup.

**Comment by honitos** [comment]
As I am rewritting hugh parts of the editor, this problem will be fixed after finishing that work.

**Comment by honitos** [comment]
fixed with V3.9.0

**Comment by stevetronic** [comment]
Super, danke!
