### ISSUE TITLE
FPU Optimisation via Uae

### ISSUE THREAD

**Issue by NickDevoctomy** [AmiBlitz/AmiBlitz3#17]
Hi there,

Please forgive me if this is a stupid question, I installed Amiblitz 3 onto my Workbench 3.1 OS install by copying it to "system:programs/AmiBlitz3" and then copying the contents of the Lib folder to "system:libs". Lastly I added the following to my workbench startup-sequence,

```
Assign >NIL: Blitz3: System:Programs/AmiBlitz3
```

I mention this first just incase I misread the instructions from the readme.md, but everything seems to load up great, no error messages.

I'm going through the samples and notice that ones that have "**optimize 7**" specified, fail to compile. They show the error...

![image](https://user-images.githubusercontent.com/13888247/105607694-345f3900-5d98-11eb-903f-95770a4d7273.png)

I have the FPU enabled for Uae, so am wondering if I have done something wrong or if maybe it just requires a real amiga to do this? My chipset settings are below, I haven't gone into any advanced settings and changed those, so they are still default,

![image](https://user-images.githubusercontent.com/13888247/105607718-5c4e9c80-5d98-11eb-9934-fcd8b1ecba80.png)

Thanks for your time.

**Comment by honitos** [comment]
As I develop on WinUAE, it should work.

An assign is not necessary, as the compiler creates the Assign at runtime that means you can have different AB3-Installs at the same time!

Did you copy the deflibs and acidlibs files a well?
I patched some internal routines to recognize the FPU.

**Comment by honitos** [comment]
I cann ot reproduce this beahaviour. It detects the FPU correctly.
