### ISSUE TITLE
Label and apostrophe

### ISSUE THREAD

**Issue by Nju79** [AmiBlitz/AmiBlitz3#19]
I've problems to concatenating labels. When I use the third key from right the IDE change this character automatically to "4". When I use Shift + this key (same as the apostrophe on the first key in left in the row) then the compiler tell me he can't find the concatenated label.

What's the right apostrophe on the keyboard to use this feature?  Or is this a bug?

**Comment by Nju79** [comment]
After one year I can't remember it anymore. In my records I only find the hint that an optional apostrophe in front of a label (e.g. 'myLabel) expands the corresponding label. What exactly is meant by this, I can't find in the AmiBlitz documentation anymore and, as I said, I have forgotten. :(

**Comment by honitos** [comment]
Ah, yes, now I know...

The apostrophe concats the label with the last label to realize "local" labels".


That means you can have same label twice in the code.

For example:

label1:
`exit:

label2:
`exit:

... as the compiler automatically combines the labels so they are different.

On the original amiga keyboard the apostrophe may be reached by this key:
![grafik](https://user-images.githubusercontent.com/36992035/161970007-c4273d13-3bb2-43f5-b379-a0d099eeeae8.png)

On WinUAE it is normally mapped to the key called "grave" (above the TAB-key).

Information about that behaviour may be found in the AmiBlitz3-Guide at "Syntax" and there under "2.1.1 Labels".
