### ISSUE TITLE
dbl_simple_01.ab3 crashes when executed

### ISSUE THREAD

**Issue by deuteros76** [AmiBlitz/AmiBlitz3#2]
The source program dbl_simple_01.ab3  crashes when is executed. 
![unamiga1200aga-crop-1912192216-01](https://user-images.githubusercontent.com/4990468/71211815-36f78100-22b0-11ea-840a-0e7015577d74.png)

Tested using Amiblitz3 3.7.0 and 3.7.2 under FS-UAE 2.8.3 on Linux

```
# FS-UAE configuration saved by FS-UAE Launcher
# Last saved: 2019-12-19 22:35:10
[fs-uae]
amiga_model = A1200/3.0
bsdsocket_library = 0
chip_memory = 2048
cpu = 68030
fast_memory = 8192
floppy_drive_speed = 400
hard_drive_0 = amigawave.hdf
hard_drive_1 = Exchange
hard_drive_2 = Work
kickstart_file = KICK_unamiga.rom
zorro_iii_memory = 32768
```

**Comment by honitos** [comment]
I found the reason for that. Most examples using the doublebuffer-include (dbl) need gfxcards.
There is a function **BestCModeIDTagList_** that is used alot there that is only available with a present cybergraphics.library. As I don't have an easy alternative yet, I can not fix that problem right away.

**Comment by deuteros76** [comment]
That makes sense as I'm emultaing an AGA machine. 
I'm not using this function  when I code in Blitz Basic 2.1 but I have a question about this, is there a way (function) to know if there is a gfxcard or ECS/AGA chipset?

**Comment by honitos** [comment]
The ElmoreHardwareLib provides a command "CheckAGA" that returns true on these machines.

**Comment by honitos** [comment]
I am going to close that bug, as it is demo-code related and not Compiler or  IDE related.
