### ISSUE TITLE
FPU detection

### ISSUE THREAD

**Issue by T0lk13n** [AmiBlitz/AmiBlitz3#25]
First...Thanks for the update! Thanks so much!

Now....testing Ab3.9 examples in my A1200 blizzard 060 aos 3.2 doesnt detect my fpu.
When optimize is set to use FPU  a "no FPU present" error is shown.

**Comment by T0lk13n** [comment]
For completeness, I use thor's mmu libs.

**Comment by honitos** [comment]
Can you please try "ProcessorFPU" command, if it detects the FPU right?

**Comment by honitos** [comment]
I don't now why, but testing on WinUAE with 68060 emulation works fine.
Can you how me the contents of the execbase's AttnFlags please?

You can get them via this code:

```
*ebase.ExecBase = execbase
NPrint "Attnflags: " + Bin$(*ebase\AttnFlags)
NPrint Processor, " - " , ProcessorFPU

```

**Comment by T0lk13n** [comment]
Sorry but I cant compile that code.
I have tried check_processor.ab3 in ab3 sources/test/ and it shows this:

000051DC
000051DC
11111111111111111000000011111111
11111111111111111000000011111111
11111111111111111000000011111111
cpu 5
fpu 4


I will try with another 68060.library to see if there is other result.

**Comment by T0lk13n** [comment]
I have tried with libs from phase5 and check_processor.ab3 showns the exact same result BUT Optimize seems to detect the FPU and can compile the source.
So something happends with Thor's libs and ab3 in my system. Weird as AttnFlags are identical.  Would be nice if anyone can test it too.

**Comment by honitos** [comment]
interesting as the asm part of the check_processor-source is the same as in optimize.
I extracted it to test several cpu/fpu combinations.
Weird.

**Comment by honitos** [comment]
I found a bug within the fpu-detecting routine. It mostly worked up to 68040 correctly, but failed on the internal 68060 cpu.
I updated the blitzlibs checking for FPU, (hopefully) fixed with v.3.8.1
