### ISSUE TITLE
Reset in second AB3 session

### ISSUE THREAD

**Issue by T0lk13n** [AmiBlitz/AmiBlitz3#27]
If by error (or not) you try to run a second instance of AB3.9 you get an "Unable to open screen" error (I have a clone WB setting) and then the whole system resets.

Amiga 1200 060 AOS 3.2.

**Comment by honitos** [comment]
I can reproduce that behaviour.

**Comment by honitos** [comment]
PED does not check if a pubscreen with the same name is already opened and can not handle this.
I improved the checking but unfortunately you still can not open a second instance with a pubscreen.
The second instance will close now clearly.

**Comment by honitos** [comment]
closed with V3.9.1

**Comment by T0lk13n** [comment]
Well...I dont really need a second instance but for security os good you hvae fixed it. Thanks!

**Comment by stevetronic** [comment]
Cool, thanks honitos.
