### ISSUE TITLE
AB3 fails to work in MorphOS

### ISSUE THREAD

**Issue by T0lk13n** [AmiBlitz/AmiBlitz3#28]
I know AB3 is aimed to work with classic machines but until now it worked nice in MorphOS.
With this latest version 3.9 the IDE goes to meditating only by loading a source file.
I can see morphOS debug log but I cant understand it.
Hope that in the future it works again.

**Comment by honitos** [comment]
you could enable the internal logging via tooltype (see tooltypes at the end).
Cann you provide me the last entries of the log ?

**Comment by honitos** [comment]
reproduced on MorpOS 3.14

**Comment by honitos** [comment]
fix for #30 solved also that bug!
