### ISSUE TITLE
Amiga reboots if try to compile and run without Save first

### ISSUE THREAD

**Issue by T0lk13n** [AmiBlitz/AmiBlitz3#29]
Run AB3
Write any code (print "hello")
Compile and run
In Pass 1: Building Executable system crash and Amiga reboots

**Comment by Nju79** [comment]
I can confirm this (WinUAE, AOS 3.2).

**Comment by stevetronic** [comment]
No problem on my machine. No crash - no problem:
Amiblitz 3.8.0
Winuae, A1200, OS3.1 (ClassicWB)
Just for reference/bug hunting.

**Comment by honitos** [comment]
yes, was a problem with LOAD_LAST_SOURCE.
Problem will be fixed with v3.9.1
