### ISSUE TITLE
MuForce hits each time write in the editor

### ISSUE THREAD

**Issue by T0lk13n** [AmiBlitz/AmiBlitz3#30]
There is an illegal memory access each time something is written in the editor.
Always the same hit .Dont know if it is relevant but sure not ideal ;)
Amiga 1200 060 AmigaOs 3.2.1

28-mar-22  21:13:42
BYTE WRITE to  0000016F        data=00         PC: 76A4A6F6
USP : 76982E84 SR: 0004  (U0)(-)(-)  TCB: 76905E10
Data: 00000001 0000016F 00000000 00000000 76AE0000 00000003 000F4240 0000003A
Addr: 76905F34 76E7B7A4 767D7C60 76E80E14 76F59972 767DF958 000051DC 001FFFF4
Stck: 00000000 00000000 00000068 00000000 76AE0000 00000003 000F4240 0000003A
Stck: 76E84E1D 76E7B7A4 76E84E1D 76E80E14 76E84E14 767DF958 000051DC 00000068
Stck: 76A4B63A 00000000 76E7B7A4 76E7B7A4 76E84E1D 76E80E14 000051DC 76A2F598
Stck: 76A2EFC8 76820A82 761944EC 0007D000 416D6962 6C69747A 33000000 0002C758
PC-8: A57A1030 19902200 4CDF0001 488148C1 D2BC0000 00FA92BC 00000001 343C0000
PC *: 11821990 20790000 00042068 01142068 003AD1FC 00000040 214C0004 4CE87FFE
76a4a6d2 :  223c 76a4 a57a             move.l #$76a4a57a,d1
76a4a6d8 :  1030 1990                  move.b (za0,d1.l),d0 ;extended opcode
76a4a6dc :  2200                       move.l d0,d1
76a4a6de :  4cdf 0001                  movem.l (a7)+,d0
76a4a6e2 :  4881                       ext.w d1
76a4a6e4 :  48c1                       ext.l d1
76a4a6e6 :  d2bc 0000 00fa             add.l #$fa,d1
76a4a6ec :  92bc 0000 0001             sub.l #$1,d1
76a4a6f2 :  343c 0000                  move.w #$0,d2
76a4a6f6 : *1182 1990                  move.b d2,(za0,d1.l) ;extended opcode
76a4a6fa :  2079 0000 0004             movea.l $4,a0
76a4a700 :  2068 0114                  movea.l $114(a0),a0
76a4a704 :  2068 003a                  movea.l $3a(a0),a0
76a4a708 :  d1fc 0000 0040             adda.l #$40,a0
76a4a70e :  214c 0004                  move.l a4,$4(a0)
76a4a712 :  4ce8 7ffe 0008             movem.l $8(a0),d1-a6
Name: "Amiblitz3"

**Comment by honitos** [comment]
I can not reproduce this behaviour.
I do not get any hits - maybe I forgot who to use all these tools...

I use WinUAE with 68030/MMU/OS3.2.1.
After SetPatch I startet SegTracker and COP.

After booting I tried Sashimi without any hits.
Starting MuForce freezes the system immediately. I have no other patches or tools installed.

**Comment by T0lk13n** [comment]
MuForce needs mmu.library from here http://aminet.net/package/util/libs/MMULib

I start workbench, execute muforce and the ab3. Nothing else.

Using  the classic Enforcer shows the same hit...

**Comment by T0lk13n** [comment]
With segtracker and Enforcer we can see that PED hits. It shows the hunk and offset.
With FindLine we should know the problematic line but for that the exe needs debug symbols.
Im not used to these tools but should be ;)

**Comment by honitos** [comment]
Problem solved with v3.8.1

**Comment by T0lk13n** [comment]
Sorry but not in my system :(

**Comment by honitos** [comment]
Sorry, T0lk13n, I attached an LHA-archive without updated PED-executable.
Please download and test again.
