### ISSUE TITLE
Remember Saved crash

### ISSUE THREAD

**Issue by T0lk13n** [AmiBlitz/AmiBlitz3#33]
AB3.9.1 amigaOS 3.2.1 Amiga 1260

"Remember Saved" ticket in IDE  preferences.
Go to "Source File" menu and system crash.

**Comment by honitos** [comment]
I hope this caused by the not updated executable in the package and may be solved by just replacing the PED-executable...

**Comment by T0lk13n** [comment]
I have updated and ít solved the problem in MorphOS but not in my a1200.
Cant view the DEBUG LOG cos system freeze :/

**Comment by T0lk13n** [comment]
You are right! You can close this issue too ;)
