### ISSUE TITLE
Click mouse and select enforcer hits

### ISSUE THREAD

**Issue by T0lk13n** [AmiBlitz/AmiBlitz3#35]
Amiga 1200 060 AOS 3.2.1 AB3.9.1

Click left mouse in the editor and move mouse as to select text. 
Then  an  Enforcer (MuForce) hit appear.
It corrupt screen title and if I try to write something it hit new enforcers hits (MuForce shows Alert! message) and system starts to fail.

If you cant reproduce it I can send  enforcer log text.

**Comment by honitos** [comment]
reproduced: read of a non existing IntuiMessage after GetMsg().
fixed with v3.8.2
