### ISSUE TITLE
Wrong character in editor

### ISSUE THREAD

**Issue by T0lk13n** [AmiBlitz/AmiBlitz3#36]
Amiga 1260 AOS3.2

Will try to explain with an example.

Write in the editor this:

==================
push delete button and suddenly that string become this
== = = = = = = = = = =

Another example:
Write this:
ççççççççççççççç
push delete button and it transform to
ggggggggggggg

**Comment by honitos** [comment]
I can not reproduce this behaviour.

**Comment by T0lk13n** [comment]
I can replicate it in MorphOS and AOS3.2.1 with latest ab 3.9.4.

**Comment by T0lk13n** [comment]
I see it happends with all spanish characters like ¿, ñ, ¡

**Comment by theotheoderich** [comment]
It happens also with german "Umlaute"
![grafik](https://user-images.githubusercontent.com/25158717/178103866-e62084da-3e27-4365-a26b-9fb42f9ae1e7.png)

It also happens when using this characters in a comment.
Thsi behaviour can be reproduced in AB 3.8 and AB 3.9.4.

**Comment by honitos** [comment]
This is due to the system, tokens are stored in the code: all characters above 127 will be detected as a token, if it turns out not to be a token, bit 7 will be cleared resulting in an different character...
