### ISSUE TITLE
Suggestion: Load last source

### ISSUE THREAD

**Issue by stevetronic** [AmiBlitz/AmiBlitz3#38]
Amiblitz3 holds a list of last sourcecodes in the "Source File" menu. Using Amiga 1-5 you can load the last 5 sourcecodes via hotkey.

However when the last file already is open and you press Amiga 1 the Ide will switch focus to this sourcecode tab BUT it will NOT reload or refresh the file,
which would be incredibly handy when you edit your source externally, for example using Notepad++. In this case, currently you have to click "open", select the file and confirm.

Suggestion:
As this is process is repeated often when using an external editor it would be very useful if the "Amiga 1" hotkey could reload/refresh the source file.

**Comment by Nju79** [comment]
Very good suggestion!

**Comment by honitos** [comment]
If you use an external editor, why do you open the IDE?
You could use AB3 in cli-mode to compile the source.

**Comment by Nju79** [comment]
Is there any documentation about the cli mode? How can I use the cli mode?

**Comment by honitos** [comment]
just run ab3 in a shell.

![grafik](https://user-images.githubusercontent.com/36992035/176401633-c9417b5c-c725-4a2c-af1d-05014eb0c1a9.png)
