### ISSUE TITLE
Inline Help MorphOS

### ISSUE THREAD

**Issue by T0lk13n** [AmiBlitz/AmiBlitz3#39]
I have assigned the help key to f12 in MorphOS.
The inline amigaguide help is showed with shift+f12 but using the tooltype
 
command1="Blitz3:Tools/ViewGuide FILE "%f" FIRSTNODE "%t" SCR=%s"

in AB3HelpViewer doesnt show the right @node.

I have chaged it to use OpenGuide by  Thomas Igrack this way

command1="sys:s/OpenGuide "%f" "%t""

and now is ok.

Only happends in MorphOS machines.

**Comment by honitos** [comment]
Ok, will close it.
