### ISSUE TITLE
Software-Failure when using the "Save & Close" button in the IDE-preferences after a change in AB 3.9.3

### ISSUE THREAD

**Issue by theotheoderich** [AmiBlitz/AmiBlitz3#42]
WinUAE JIT, Kick 3.1, A4000 Chipset, AGA
AB3 Screen: PAL Super HighRes Interlace

Reproducible error:
- Open the IDE-Preferences
- For example enable the "No Localization" in the ""General Settings"
- Click on the "Save & Close" button
- --> Amiblitz3 Software-Failure Error-Number 80000020

Workaround:
First click on "Use & Close", open the preferences again, than click on "Save & Close".
Settings will be saved without Software-Failure.

**Comment by T0lk13n** [comment]
Replicated in Amiga 1260 with AOS3.2

**Comment by honitos** [comment]
fixed with v3.9.4
