### ISSUE TITLE
Keywords shown in Large Font

### ISSUE THREAD

**Issue by sikosis** [AmiBlitz/AmiBlitz3#43]
![unknown-7](https://user-images.githubusercontent.com/1312559/176571840-bb422ec8-74b1-4e61-a66f-07e3ddc05655.png)

**Comment by AdamENESS** [comment]
![image](https://user-images.githubusercontent.com/69882482/176578287-691d7228-2a0e-492f-a333-c397a2a60b7b.png)

**Comment by honitos** [comment]
Ah, there is a font set in the settings, that is not available on your system.
Please go to the preferences and change the sourcefont to a suitable one:

![grafik](https://user-images.githubusercontent.com/36992035/176608761-0a6b7a31-5c75-4ec6-b5a9-a23805e2bd2b.png)


I am going to change the default settings to topaz.font - thanks for the hint.
