### ISSUE TITLE
Enforcer hit starting AB3

### ISSUE THREAD

**Issue by T0lk13n** [AmiBlitz/AmiBlitz3#44]
Executing AB3 it show the next Enforcer Hit in Amiga 1200 060 AOS3.2.1.
MorphOS also showns a hit.

MuForce hit! Bad program!?
07-jul-22  18:55:04?
LONG WRITE to  00000000        data=00000000   PC: 7874F38C?
USP : 7884A7A8 SR: 0014  (U0)(-)(-)  TCB: 7882B2D0?
Data: 00000003 00000000 00000000 00000000 00000000 00000000 00000000 00000000?
Addr: 786140D8 00000000 7860C936 78DB3CE4 00000000 78443000 000051DC 781F2D74?
Stck: 78744F80 781944EC 0001F400 416D6962 6C69747A 33000000 00036D68 1E17EA75?
Stck: 4E55FFFC 48E7303A 286D0010 266D0014 4282244D 252C0004 2C79785F AD62204A
Stck: 4EAEFFD0 20404A80 670000AE 22280004 20100680 7FE7FDDE 7614B680 65DA303B
Stck: 0A064EFB 0002008A 0082007A 0072006A 0062005A 0052004A 0042FFD2 FFD2FFD2
----> 7874F38C - "Amiblitz3"  Hunk 0000 Offset 0002A17C
----> 78744F80 - "Amiblitz3"  Hunk 0000 Offset 0001FD70
----> 781944EC - "LDM - dos 47.30 (2.12.2021)"  Hunk 0000 Offset 00000524
----> 785FAD62 - "LIBS:wizard.library"  Hunk 0001 Offset 0000038A
PC-8: 82CE2F00 221F2C6D 80244EAE FFA660FF FFFFFDF8 7003222D 8304243C 00000000
PC *: 21821990 202D82F8 223C0000 00014481 B08167FF 0000001A 202D82F8 4EB97873
7874f36a :  202d 82ce                  move.l -$7d32(a5),d0
7874f36e :  2f00                       move.l d0,-(a7)
7874f370 :  221f                       move.l (a7)+,d1
7874f372 :  2c6d 8024                  movea.l -$7fdc(a5),a6
7874f376 :  4eae ffa6                  jsr -$5a(a6)
7874f37a :  60ff ffff fdf8             bra.l $7874f174 ;extended opcode
7874f380 :  7003                       moveq.l #$3,d0
7874f382 :  222d 8304                  move.l -$7cfc(a5),d1
7874f386 :  243c 0000 0000             move.l #$0,d2
7874f38c : *2182 1990                  move.l d2,(za0,d1.l) ;extended opcode
7874f390 :  202d 82f8                  move.l -$7d08(a5),d0
7874f394 :  223c 0000 0001             move.l #$1,d1
7874f39a :  4481                       neg.l d1
7874f39c :  b081                       cmp.l d1,d0
7874f39e :  67ff 0000 001a             beq.l $7874f3ba ;extended opcode
7874f3a4 :  202d 82f8                  move.l -$7d08(a5),d0
7874f3a8 :  4eb9 7873 3342             jsr $78733342
Name: "Amiblitz3"  Hunk 0000 Offset 0002A17C

**Comment by honitos** [comment]
solved with V3.9.5
