### ISSUE TITLE
Delays in mouse clicks within the program code in AmiBlitz 3.9.4

### ISSUE THREAD

**Issue by theotheoderich** [AmiBlitz/AmiBlitz3#45]
When i click into the program code the cursor jumps to the selected position...that is fine.

But immediately after that I click on another place in the program code, nothing happens.
It takes a moment until I can click somewhere again and the cursor jumps to the position.

If I click several times in quick succession within the program code, nothing happens at all.
Only when I have not clicked anything for a moment, I can click a position again and the cursor jumps to this position.

It feels like there is an "internal counter" that counts down after each click.
This delay does not exist in AB 3.8 and is very annoying.

**Comment by honitos** [comment]
@theotheoderich I thought this problem was related to V3.9.3 and has been solved.
