### ISSUE TITLE
Window for creation of an executable file occurs on the wrong screen.

### ISSUE THREAD

**Issue by theotheoderich** [AmiBlitz/AmiBlitz3#46]
I am running tAmiBlitz on a PAL:SuperHighRes Interlace Screen in WinUAE.

When i want to create an executable file i go to the compile menu and choose "Create executable file" (i am using the german version, there is it called "Ausführbare Datei Erstellen").

Then a compiling window is visible, but nothing happens.
This is, because the window, where you can choose the path and the name for the exe file, occurs on the Workbench Screen.
So it is not visible from AmiBlitz.

Other file windows like "Open" or "Save as" are displayed correct on the AmiBlitz 3.9.4 screen.

**Comment by honitos** [comment]
reproduced - will be fixed in v3.9.5

**Comment by honitos** [comment]
fixed with v3.9.5
