### ISSUE TITLE
Compiled files are bigger in AB 3.9.4 as in AB 3.8

### ISSUE THREAD

**Issue by theotheoderich** [AmiBlitz/AmiBlitz3#47]
I used the exactly the same program-code and exactly the same AmiBlitz settings in AB 3.8 and AB 3.9.4.
First i created an executable file and then i used the compilier function to create a minimized executable file.
The used libs are also the same in both AmiBlitz versions.

The result is:
AB 3.8
Filesize 472.768 Bytes

AB 3.9.4
Filesize 487.736 Bytes

This is a difference of nearly 15 kb....that is very much.

**Comment by honitos** [comment]
I guess there is on library that is bigger than with the V3.8 release or there is a lib that has a new dependency to another lib.
In the latter case, the lib that is depended by the other lib will be linked in total to the executable.

Do you have many blitzlibs in use with your project ?
You can examine the used libs of the current loaded sourcefile by using the "Libs"-Tab in the source browser window.

![grafik](https://user-images.githubusercontent.com/36992035/178282495-9c64955c-d046-4f16-81d0-22636c51ae03.png)

**Comment by honitos** [comment]
Can you provide me the list of used blitzlibs (screenshot is sufficient)?
Then I check if one of them has been changed.

**Comment by theotheoderich** [comment]
Sure, here is a screenshot from AB 3.8.

![grafik](https://user-images.githubusercontent.com/25158717/178489267-c625ea93-0037-41a0-a3bd-62214b5ab7b7.png)

**Comment by Nju79** [comment]
I cannot confirm the behavior. For me, the exe file in v3.9.4 is smaller than in v3.8. However, my exe file is only about 130kb "small".
