### ISSUE TITLE
Deleting a line corrupts source

### ISSUE THREAD

**Issue by theotheoderich** [AmiBlitz/AmiBlitz3#49]
Strange problem. Sometimes AB is confused. I can not descripe exactly what happend, but i deleted some code rows, then the black code text disapeard and the text cursor changed from the standard black to green color.
After that it was not possible to do anything in AB, so i had to reset.

After loading the file again it was broken.
The last line i was working on before the reboot looks very strange. (See screenshot / marked in yellow).
![grafik](https://user-images.githubusercontent.com/25158717/178162601-bb5f9eb3-fab3-4294-9665-5ae3013ad3e7.png)

All code beyond this row is gone, so i had to restore the .bak file.

This evening this happend three time within one hour....
Yesterday i worked four hours with AB 3.9.4 without this problem....strange.

**Comment by honitos** [comment]
solved with v3.9.5
