### ISSUE TITLE
AmiBlitz3 in Amiga Forever

### ISSUE THREAD

**Issue by UAERetroGamer** [AmiBlitz/AmiBlitz3#50]
Hi,

I was wondering if AmiBlitz3 can have a version for Amiga Forever.

**Comment by T0lk13n** [comment]
But Amiga Forever is basically a frontend for winuae.
Dont understand why a different version than the normal one  is needed.

**Comment by UAERetroGamer** [comment]
Amiga Forever is not recognizing the .lha 

Is there a special way to install it in Amiga Forever ?

**Comment by T0lk13n** [comment]
Copy the whole ab3.lha package to the amiga system you use with Amiga Forever and you can decompress there with lha. Or decompress it with unrar in windows and copy it to the system in AF.
Perhaps you ask for a HDF with AB3 installed?

**Comment by honitos** [comment]
This issue is no related to AmiBlitz3 software.
