### ISSUE TITLE
Bug with borders on windows

### ISSUE THREAD

**Issue by Nju79** [AmiBlitz/AmiBlitz3#51]
System: FS-UAE, Kickstart 3.2.1 & Workbench 3.2.1 and AB3.9.4
First of all: The behavior does not occur in v3.8.

Code:

WBStartup
FindScreen 0
Borders On
TextGadget 0, 10, 30, 0, 3, "Close"
Borders 16, 8 
Window 0,0,0,200,200,$1008, "Connect - Creator", 0, 0, 0
MouseWait
End

![Border issue](https://user-images.githubusercontent.com/32636068/186230574-0edb28e9-8596-40a7-a328-2c05d4cac700.png)

**Comment by honitos** [comment]
This is really odd.
No idea - I am goin to investigate that problem.

**Comment by honitos** [comment]
Sorry for that, there was a bug in the disassembled source of intuifontlib that prevented the lib to return the init font attributes...
fixed with v.3.9.6
