### ISSUE TITLE
System freeze when select and press key

### ISSUE THREAD

**Issue by T0lk13n** [AmiBlitz/AmiBlitz3#52]
Click left mouse button in the editor and move mouse as to select.
Push any key and system freeze completly.
Happends in Amiga 1260 aos 3.2 and MorphOS 3.17

It always happends if an empty area is selected and only sometimes with text selected.

**Comment by honitos** [comment]
will be fixed with v3.9.6

**Comment by T0lk13n** [comment]
Now works great minus a problem.
If you select with mouse and press delete the cursor goes one position less than the selected area.
If the selected area starts at position 1 and press delete the cursor goes to Line number position with a crash.
