### ISSUE TITLE
Enforcer Hit each time a key is pressed

### ISSUE THREAD

**Issue by T0lk13n** [AmiBlitz/AmiBlitz3#53]
With even an empty editor, each time you press a key there is an enforcer hit.
Tested in MorphOS and AOS 3.2.

LONG WRITE to  00000000        data=00000000   PC: 7687E9B2
USP : 767D1534 SR: 0004  (U0)(-)(-)  TCB: 767B2060
Data: 00000003 00000000 00000000 00000000 00000000 FFFF000A FFFFFFE4 00000033
Addr: 768F9626 76936D24 7692EF72 7692FFD0 76D89B7A 765D8C68 7601DACC 761F2D74
Stck: 7687E51A 766CCAD4 761944EC 0001F400 416D6962 6C69747A 33000000 00036D68
Stck: 1D97B775 4E55FFFC 48E7303A 286D0010 266D0014 4282244D 252C0004 2C79765E
Stck: E162204A 4EAEFFD0 20404A80 670000AE 22280004 20100680 7FE7FDDE 7614B680
Stck: 65DA303B 0A064EFB 0002008A 0082007A 0072006A 0062005A 0052004A 0042FFD2
----> 7687E9B2 - "Blitz3:System/PED"  Hunk 0000 Offset 00038E52
----> 7687E51A - "Blitz3:System/PED"  Hunk 0000 Offset 000389BA
----> 766CCAD4 - "Amiblitz3"  Hunk 0000 Offset 00020ACC
----> 761944EC - "LDM - dos 47.30 (2.12.2021)"  Hunk 0000 Offset 00000524
----> 765EE162 - "LIBS:wizard.library"  Hunk 0001 Offset 0000038A
----> 7614B680 - "LDM - graphics 47.10 (31.10.2021)"  Hunk 0000 Offset 00008304
PC-8: 19902400 4CDF0003 48E7E000 7003223C 76846370 20301990 26004CDF 0007D483
PC *: 21821990 30397684 5FB533C0 76846027 7003223C 768AE426 20301990 48E78000
7687e992 :  1990 2400                  move.b (a0),$0(a4,d2.w*4) ;extended opcode
7687e996 :  4cdf 0003                  movem.l (a7)+,d0-d1
7687e99a :  48e7 e000                  movem.l d0-d2,-(a7)
7687e99e :  7003                       moveq.l #$3,d0
7687e9a0 :  223c 7684 6370             move.l #$76846370,d1
7687e9a6 :  2030 1990                  move.l (za0,d1.l),d0 ;extended opcode
7687e9aa :  2600                       move.l d0,d3
7687e9ac :  4cdf 0007                  movem.l (a7)+,d0-d2
7687e9b0 :  d483                       add.l d3,d2
7687e9b2 : *2182 1990                  move.l d2,(za0,d1.l) ;extended opcode
7687e9b6 :  3039 7684 5fb5             move.w $76845fb5,d0
7687e9bc :  33c0 7684 6027             move.w d0,$76846027
7687e9c2 :  7003                       moveq.l #$3,d0
7687e9c4 :  223c 768a e426             move.l #$768ae426,d1
7687e9ca :  2030 1990                  move.l (za0,d1.l),d0 ;extended opcode
7687e9ce :  48e7 8000                  movem.l d0,-(a7)
Name: "Amiblitz3"

**Comment by honitos** [comment]
reproduced, will be solved with 3.9.6.
