### ISSUE TITLE
TextGadget: Visual clickbox (Toggle) is to high

### ISSUE THREAD

**Issue by Nju79** [AmiBlitz/AmiBlitz3#54]
System: FS-UAE, Kickstart 3.2.1 & Workbench 3.2.1 and AB3.9.4
First of all: The behavior does not occur in v3.8.

I've created a TextGadget without Borders. If I mousedown on this TextGadget in v3.9.4 the toggle color box seems to have more the double high of the control.

**Comment by honitos** [comment]
same problem as in #51 - fixed with v3.9.6

**Comment by honitos** [comment]
@Nju79 I can not contact you directly so via this comment:
I built a pre-release of AB3 (v3.9.6) - if you want you can try if your issues are solved...

**Comment by Nju79** [comment]
Solved
