### ISSUE TITLE
Applications want to load cybergraphics.library

### ISSUE THREAD

**Issue by Nju79** [AmiBlitz/AmiBlitz3#55]
I've compiled several apps with gadgets and snoop them. SnoopDos shows me that the application is failed to load cybergraphics.library.
I checked the libs in the IDE there is no cybergraphics.library in the list. However, the application starts and particullary working (there are some other issues with gadgets...).
![Ohne Titel](https://user-images.githubusercontent.com/32636068/187164446-36a4427e-4f27-46b7-9dd2-7ce50b1a3fed.jpeg)

**Comment by honitos** [comment]
screenslib tries to open cybergraphics.library if the system that runs the executable is lower than OS3.0.

In case you want to open 24bit screens, "cybergraphics.library" is used to determine the best screen mode, as the amigaOS <3.0 does not support 24bit screens.

So the behaviour is expected.
