### ISSUE TITLE
Missing inbuild help for RAWSTATUS command

### ISSUE THREAD

**Issue by theotheoderich** [AmiBlitz/AmiBlitz3#65]
In AB 3.9.7 the inbuild help for RAWSTATUS is not working when pressing HELP + SHIFT.
In AB 3.8 a page will be opend explaning all RawKeys.

**Comment by theotheoderich** [comment]
The inbuild help (Shift + HELP key) is not working, regardless which command.
Only the short command reference via the HELP key is working (shown in the top bar of the editor).

**Comment by T0lk13n** [comment]
Are  you using CloneWB  in ab3 enviroment prefs?
If I clone WB cant get any help. Usong WB or other custom screen the help works.

**Comment by theotheoderich** [comment]
No, i am using a PAL Screen: SuperHighRes.
But your comment helped me a lot :-)
I enabled the checkbox for "Public Screen" and now i have a working ingame-Help.
Thank you very to get me on the right track.

**Comment by T0lk13n** [comment]
Fantastic! 
Honitos has now more info to fix it.

**Comment by honitos** [comment]
this one was tricky, as I had to check the whole toolchain: PED > AB3HelpViewer > Viewguide
fixed with next version

**Comment by honitos** [comment]
There is a bug in the tooltype "command1" of "Tools/AB3HelpViewer".
The Tooltype must read 
command1="Blitz3:Tools/ViewGuide FILE "%f" FIRSTNODE "%t" SCR="%s""

The Tooltype lacks the last ".
