### ISSUE TITLE
Compiler Errors in an Include Open the Include even when it's already open

### ISSUE THREAD

**Issue by daedalus2097** [AmiBlitz/AmiBlitz3#67]
When compiling and a compile-time error is detected in an Included source file, the source file is opened in a new tab, even if the file is already open. This means there are multiple copies of the same source file open, which can lead to confusion and lost edits if you start editing one.

**Comment by theotheoderich** [comment]
I have the same problem ;-)

**Comment by honitos** [comment]
fixed in next version
