### ISSUE TITLE
Saving as "filename.AB3" corrupts code when loading

### ISSUE THREAD

**Issue by stevetronic** [AmiBlitz/AmiBlitz3#7]
After saving a program with the file extension ".AB3" in capital letters it will not load again
correctly (as all tokens then are "?").

Note: test this using the source file-open dialog, as using the "last files list" doesn't show the problem.

Details:
- it is saved as a tokenized file without XTRA header (also much smaller in filesize)
- an .xtra file is saved besides

I haven't tested this a lot at the moment but I think as a workaround renaming the file (and xtra) to .bb2 seems to help (so you can load it again).

**Comment by honitos** [comment]
Resolved with V3.7.4
