### ISSUE TITLE
Commands Not Recognised - 3.9.8

### ISSUE THREAD

**Issue by DisasterIncarnate** [AmiBlitz/AmiBlitz3#72]
My previous issue of AB3 files freezing the program when loaded have been resolved, i can load my projects made on 3.8.1 now, however when they load, all the commands that should turn blue remain black text, attempting to compile the program results in the compiler complaining about "garbage" being present and points to the commands which should be blue but are black.

If i manually remove 1 letter from those commands and retype the removed letter, the command turns blue as it normally should be, thsi is obviously a massive pain for large programs.

For example **NPrint "Hello World"** should have **NPrint** highlighted in blue, but its not, its just black and on compile the compiler says the black colored NPrint is garbage.

The example programs do not suffer this issue so at a guess its something to do with loading/recognising older code again?

**Comment by honitos** [comment]
Are your source files standard *.ab3 files or other filetypes?
Can you provide me an example file ?

**Comment by DisasterIncarnate** [comment]
the example i gave for my previous issue should also have this behaviour, basically anything created/saved with 3.8.1 as AB3 has this behaviour for me.

Relink for old example file: https://file.io/5grInc1Dl9QT
Picture showing issue: https://i.imgur.com/s12Atux.png

still having to use 3.8.1 as my day to day amiblitz version.

**Comment by honitos** [comment]
I see the problem.
The sourcefile is *NOT* an AB3 file, just a normal text file where the extention has been changed.
Rename the extention to for example ".ab2" and it will work.

The compiler expects configuration data at the beginning of an AB3-file:
Save it with the extention of ".ab3" will add the configuration data that was previously stored in the ".xtra"-file.

**Comment by DisasterIncarnate** [comment]
hmm not sure how thats happened then, that program was made quickly, saved as AB3 on its first save and never changed since, so not sure how thats ended up as plain text, its never been plain text.

Ill try renaming my other projects as AB3 and see what happens.

**Comment by honitos** [comment]
You can check this by opening the ab3-file in another text editor. There will be lots of comments at the begining of the source file, where AB3 stores all the settings.
This is the difference between a plain text file and an ab3-file.

Even the ab2-file from AmiBlitz2 was a plain text file as there was still the xtra-file present.

**Comment by DisasterIncarnate** [comment]
ok ive had a play around with multiple files on both 3.8.1 and on 3.9.8, you seem to be correct that renaming "some" of my files lets me open them correctly in 3.9.8, and your explanation that there are differences between ab2/ab3/txt and they are handled differently now has me saving each of my projects as all 3 formats.

My issue however is that "originally" when making my projects every one of my projects were originally saved as AB3 and if i had issues with any of them, i used the editor to SAVE AS a TXT file, i never once just renamed a file so how some of my programs have ended up in what looks like the wrong format even though i havent renamed them is a mystery to me.

But still my issue is resolved, i still have no idea why my projects ended up the way they did but with your information i ended up simply copying all my AB3 projects into 2 more copies and i renamed 2 of the copies into a TXT and an AB2 then tried loading those copies into the 3.9.8 editor, and lo and behold, some of them do load up correctly and now when i am editing any of my programs, I am saving them 3 times as AB2/|AB3 and TXT, just incase i have issues again or i corrupt/break one of my programs.

So yeah my issue is resolved, just not how i expected it to be :)  thanks, i can at least use the up to date/newer versions of AmiBlitz on all my projects now, thanks for deep-diving and finding the eventual cause.
