### ISSUE TITLE
Editor speed much slower than before

### ISSUE THREAD

**Issue by Peceha** [AmiBlitz/AmiBlitz3#73]
Hi,
if you compare the speed of amiblitz editor in version 3.8.0 to the latest versions (3.9 series) you will notice HUGE drop of speed , by huge I mean it becomes hard to use at all (I'm using a1200 with blizzard 030 on 16 colors screen).
I would really like to have fun with all new stuff you are fixing/adding to amiblitz but unfortunately cannot due to speed issue.
Of course if your aim is fasters processor (ie 060) then all is ok and I understand it - but if the speed lost happened accidentally than maybe there is still a hope to bring it back ? :)
To say it short: speed of 3.8.0 = speed of 3.9 without highlighting (otherwise the 3.9 is few times slower)

Thanks.
And you are doing really a great job on that project!

**Comment by honitos** [comment]
Of course there is a slow down as the assembler code is converted to basic again.
The pure asm code is much better, it is shorter (smaller) and faster.
After I've done the conversion I am going to get it fast again. Both goals are not efforable at the same time as a hobby project :-)
