### ISSUE TITLE
ptplayer routines buggy?

### ISSUE THREAD

**Issue by PTz0uAH** [AmiBlitz/AmiBlitz3#77]
Hoi there.. as an oldschool Blitz2.1 fan I have picked up the old habit and wanted to get some things done for a demo/game for classic Amiga  (concept = play the module with the game code in the loop and mix-in game sounds on demand) which should be possible using the ptplayer routines..

The example "ptplayer.ab3" did not work "ootb"..

[BUG1?]  as the command [MTPlayFX] did not work..even after rebuilding the ptplayer.obj with vbcc so as a workaround I had to fallback using (MTSoundFX + vwait 6) which worked yet introduced some high-pitch ringing/static after the "clap" needing tot restart the program..

[BUG2?]  modules are played in repeat mode it seems yet after loading "life power.mod", a 820K module ptplayer crashes at the end with gurumeditation $8000 0004.. note: if manually quit 1 sec before end.. everything is ok..

Any hints on how to proceed?

**Comment by honitos** [comment]
I am sorry, as the ptplayerlib is just a contribution to the package, I can not support it for myself.
Please contact the author of the port here: https://github.com/E-Penguin/blitz_ptplayer?fbclid=IwAR0OhcCDXDb1MO-XFFANgpPLL03OUyBST7GlOwbrAfKTstaviXn9xrh3SlU
