### ISSUE TITLE
WindowIsOpen() not working as expected

### ISSUE THREAD

**Issue by mbergmann-sh** [AmiBlitz/AmiBlitz3#78]
simselbimsel.b = WindowIsOpen(1) results in 0 even if that wzWindow is allready opened.
Using a standard Window, the result is -1. In both cases, the function should return True instead. (AB3 v3.9.9)

User FYI:
A workaround for wzWindows would be *wzwin.Window = Peek.l(Addr Window(WZID("Window name") ) )
*wzwin > 0 - Window is open
*wzwin = 0 - Window is not open

**Comment by honitos** [comment]
The problem is that wizard.lib uses it own window management.
Checking WZWindows would require a dependency for the blitzlib "wzlib" in *any* case.
I want to avoid this.
