### ISSUE TITLE
Guru when Undelete line with a command.

### ISSUE THREAD

**Issue by FabrizioRadica** [AmiBlitz/AmiBlitz3#79]
if I delete a line with any procedure or command (Amiga+D) and then restore it (Amiga+U), everything goes to guru.

simple test:

NPRINT "Hello World"
then delete ana undelete...

**Comment by honitos** [comment]
Seems only to happen if the line you delete-undelete is the only existing source line, @FabrizioRadica can you confirm this?

**Comment by FabrizioRadica** [comment]
> Seems only to happen if the line you delete-undelete is the only existing source line, @FabrizioRadica can you confirm this?

Yes I confirm.

**Comment by theotheoderich** [comment]
I can confirm this. 
With WinUAE it crashes also the emulation (Minidump error window).

**Comment by daedalus2097** [comment]
Sorry to reopen this, but I've had 3.9.9 guru when I delete and undelete a line when there are lots of other source lines in the editor. It also happens not just with commands, but with commented lines too.

**Comment by honitos** [comment]
fixed with release of v3.9.9
