### ISSUE TITLE
IDE Unusable in non interlaced modes

### ISSUE THREAD

**Issue by sacredbanana** [AmiBlitz/AmiBlitz3#8]
I switched to non interlaced PAL mode since interlacing on my 1084S monitor is awful to look at and now some of the GUI buttons are off the screen and hence unusable, this includes the confirmation buttons in the pref screen so I am unable to switch back into interlaced mode to see the entire GUI again so its unusable. Are we able to make all the UI elements fit on the lower vertical resolution modes or at least prevent the user from using such a mode to begin with so they don't end up getting stuck like I am?

**Comment by honitos** [comment]
That is correct but it is very hard to make that requirement possible with a complex IDE and just having 200/256 lines.
I am going to add some kind of restriction in screen height selection below 480pixels...

**Comment by honitos** [comment]
Resolved with V3.7.4
