### ISSUE TITLE
PED crashes when deleting the last line

### ISSUE THREAD

**Issue by Emsgold** [AmiBlitz/AmiBlitz3#80]
When you delete the last line of a sourcecode with "Amiga-D", PED crashes.

System: FS-UAE, OS 3.2.2

**Comment by theotheoderich** [comment]
I can confirm this.
In my case this only happend, when you have to scroll down to reach the last row.
When using WinUAE this will crash the emulation.
![grafik](https://user-images.githubusercontent.com/25158717/228251161-15bdace2-0904-43ee-8629-7b84cee33c1b.png)

It does not happen, when the first row of the code is still visible.

**Comment by honitos** [comment]
fixed with release of v3.9.9
