### ISSUE TITLE
AmiBlitz3.9.9 - The search crashes the system with lines > 256 characters

### ISSUE THREAD

**Issue by theotheoderich** [AmiBlitz/AmiBlitz3#84]
The search causes a system crash if a line contains more than 256 characters.
However, this is not always visible because the lines are sometimes padded with spaces.
I noticed this when I used Notepad ++ with my code. There was a line of code with 60 characters of code and spaces up to column 261 (but I didn't write them there myself!).
After I removed all unnecessary spaces, the search works again without problems.

**Comment by honitos** [comment]
fixed with release of v3.9.9
