### ISSUE TITLE
Debugger not Starting (3.9.9)

### ISSUE THREAD

**Issue by daedalus2097** [AmiBlitz/AmiBlitz3#85]
The debugger fails to start with the latest 3.9.9. With the debugger disabled, code runs ok from the editor, but with the debugger enabled, the Shell window opens but nothing happens. Panic quit sometimes works to close the editor, sometimes crashes.

**Comment by honitos** [comment]
Did you download the current master branch?
Withe the official v3.9.9 it not happen.

**Comment by daedalus2097** [comment]
This is with the latest master. I was trying the latest master because the official release is far too unstable to be used on my setup.

**Comment by honitos** [comment]
This was related to the development progress.
