### ISSUE TITLE
Pasting a String Corrupts Editor (3.9.9)

### ISSUE THREAD

**Issue by daedalus2097** [AmiBlitz/AmiBlitz3#86]
Copying and pasting a string a couple of times within the editor causes the cursor to stop responding to the cursor keys. Pressing shift-down or shift-up to scroll by screen shows complete corruption of the editor as shown in the screengrab. Scrolling with the mousewheel leaves a trail of cursor and corruption remains.
![AB3-Corruption](https://github.com/AmiBlitz/AmiBlitz3/assets/3780680/481f5471-52d5-4239-bcd4-708dc6db85c2)

**Comment by honitos** [comment]
Did you just download the current master branch or the official Release v3.9.9?

**Comment by daedalus2097** [comment]
As with the other report, this is the latest master because the official release (Feb 23) is too unstable on my setup, which is a relatively plain OS 3.9 RTG-based setup.

**Comment by honitos** [comment]
Ah I see.
I'm going to release a v3.9.10-beta within the next couple of days to close the long gap between the last release and all the things I've done so far.

**Comment by honitos** [comment]
fixed with 3.9.10
