### ISSUE TITLE
Odd Behaviour / Change in Behaviour of Automatic Indenting (3.9.9)

### ISSUE THREAD

**Issue by daedalus2097** [AmiBlitz/AmiBlitz3#87]
Automatic indenting works ok when you start a new line from within or the end of an existing line. However, if you try to move an indented line down by positioning the cursor at the first non-whitespace character, the indent is lost. In AmiBlitz 3.8, the indent is kept. Additionally, if the cursor is placed in the very first column and try to move the line down with Enter, the line is indented beyond its current indent, so it's indented too far. There doesn't seem to be a combination that lets the indent be maintained as it was.

**Comment by honitos** [comment]
fixed with 3.9.10
