### ISSUE TITLE
Ctrl+C/Ctrl+V Vertical Pasting One Character Out (3.9.9)

### ISSUE THREAD

**Issue by daedalus2097** [AmiBlitz/AmiBlitz3#88]
Vertical copying and pasting (using Ctrl+C and Ctrl + V) produces pasted text that has an extra space to the left and is missing the last highlighted character to the right. For example, copying the word "End" then pasting in the line below produces instead " En"

**Comment by honitos** [comment]
fixed with 3.9.10
