### ISSUE TITLE
ASLFileRequest bug

### ISSUE THREAD

**Issue by pjhutch17** [AmiBlitz/AmiBlitz3#93]
If I try to use the ASLFileRequest$ function in AmiBlitz 3.7.4 I get this error:

Not enough space in PATH string.

Code to replicate it:
title$="Open file"
apath$="SYS:Work"
f$=""
pat$="#?.txt"
result$=ASLFileRequest$(title$, apath$, f$, pat$, 10, 10, 500, 550)

I tried different length strings for apath$ and f$ with no luck. Any ideas?

**Comment by pjhutch17** [comment]
I had a look at the BlitzLibs guides and the solution is to use these statements to set the max size for strings used by the functions.
MaxLen apath$=192
MaxLen f$=192

**Comment by honitos** [comment]
The functions work as designed in the blitzlib.
