### ISSUE TITLE
Building from source

### ISSUE THREAD

**Issue by k-berger** [AmiBlitz/AmiBlitz3#94]
Hi!
I was going through the repo thinking about low-hanging fruit to contribute to my favorite language of the 90s and decided by starting to clone the repo and build inside my FS-UAE from source. 
I was hitting some minor issues like include-files not being loaded (had to change the path), `progress_width` constant being removed with one of the latest commits, but still being used and things getting stuck when compiling and running from `Compiler.ab3`  but I am not sure whether I setup the environment according to "how it should be done" and refrain from creating a PR for that reason.

Is there some guidance on how to build, test and contribute on this repo?
Like
* How to setup your build-environment
* Which branch to base your work on
* What should a PR look like

Would be fun to look into some of the issues that people (and myself) are experiencing from time to time.

Thanks for any suggestion!
Great work on this by the way, keep it up 💪

**Comment by honitos** [comment]
hi @k-berger 
sorry for the long delay but I returned to AB3 just some days before.

I fixed several problems in the master-branch so it should now be possible to compile it.
Feel free to contact me if you get into trouble again.
