### ISSUE TITLE
AB 3.9.10 - Problem with Un-TAB of selected texts with CTRL + arrow keys.

### ISSUE THREAD

**Issue by theotheoderich** [AmiBlitz/AmiBlitz3#95]
Version 3.9.10 (07.11.2024)

Works:
Select text from top left to bottom right and then move it to the left using CTRL + left arrow key.

**Does not work:**
Select text from bottom right to top left and then move it to the left with CTRL + left arrow key.
The text underneath is incorrectly moved as well.

In 3.9.9 it is working the correct way.

[Short video to show the error](
https://theotheoderich.de/amiblitz/bugs/AmiBlitz3.10.Final_UnTAB_markedText.mp4)

**Comment by honitos** [comment]
fixed with v3.9.11
