### ISSUE TITLE
AB 3.9.10 - Problem when opening files with the same name in different folders.

### ISSUE THREAD

**Issue by theotheoderich** [AmiBlitz/AmiBlitz3#96]
Version 3.9.10 (07.11.2024)

I open the file “city.ab3” from directory **A**.
Now I click on the menu item Source File / Open New and open a file with the same name “city.ab3” from the backup directory **B**.

The following message appears:
Load File
The file is already open. Do you want to reload it?
Yes/Cancel

With Cancel nothing happens at all.
If Yes is selected, the file tab of “city.ab3” from directory **A** is replaced by the file “city.ab3” from directory **B**.

This is very inconvenient.
In AmiBlitz 3.9.9, the file “city.ab3” from directory **B** is opened in a new file tab, which is much more convenient.

**Comment by honitos** [comment]
problem is, the editor just compares the filename, but not the path.
will fix that immediately.

**Comment by honitos** [comment]
fixed with v3.9.11
