### ISSUE TITLE
AB 3.9.10 - Jumping to the end of a line (SHIFT + right arrow key) is not possible with long lines

### ISSUE THREAD

**Issue by theotheoderich** [AmiBlitz/AmiBlitz3#97]
Jumping to the end of a line with SHIFT + right arrow key does not work with long lines that exceed the screen width.

It then becomes “graphic garbage

Here are two short videos to show the problem:
[Video 1](https://theotheoderich.de/amiblitz/bugs/AmiBlitz3.10.Final_JumpToLineEnd.mp4)
[Video 2](https://theotheoderich.de/amiblitz/bugs/AmiBlitz3.10.Final_JumpToLineEnd2.mp4)

Please contact me, if you need further infos about these problem ;-)

**Edit:**
Even using the scroll bar at the bottom of the screen does not help to get to the end of the long line.

[Video 3](https://theotheoderich.de/amiblitz/bugs/AmiBlitz3.10.Final_JumpToLineEnd3.mp4)

**Comment by honitos** [comment]
fixed with v3.9.11
