### ISSUE TITLE
AB 3.9.10 - "End If" ist not tokenized correctly (e. g. after uncomment)

### ISSUE THREAD

**Issue by theotheoderich** [AmiBlitz/AmiBlitz3#98]
If commented-out code with “Block Uncomment” and then becomes normal code again, “End If” commands are no longer “tokenized” correctly. Only the first part, the “End”. The “If” is no longer tokenized.

This leads to a compilation error.
[Video](https://theotheoderich.de/amiblitz/bugs/AmiBlitz3.10.Final_JumpToLineEnd3.mp4)

**Edit:**
The same error occurs when "Block TAB" or "Block UnTAB" is used.

![grafik](https://github.com/user-attachments/assets/661f0dc9-991b-4159-b209-9d94a29a1551)

**Comment by honitos** [comment]
fixed with v3.9.11

**Comment by theotheoderich** [comment]
> fixed with v3.9.11
> 
> BTW. you should use "EndIf" instead of "End If" as it is the official style.

Thank you, but the shortcut STRG and E will print "End If" (refer Shrotcuts Reference) and not "EndIF" ;-)
